### PR TITLE
Dockerize development

### PR DESCRIPTION
**Pull request by ayaleloehr**
DO NOT MERGE. There are still issues here but wanted to put something up. 

This PR:
- Fully removes active-record dependencies (had been partially removed before) as well as other unused dependencies
- Moves Redis URL to an environment variable
- Adds Dockerfile and docker-compose file for spinning up a container for Rails and one for Redis

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Current issue is around moving from testing this off the VA network to testing on the VA network. This error isn't actually about this PR even, but is something about Docker running on my machine and failing to "validate certificates" when moving onto the VA network. Error is:
```
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```
Regenerating certs doesn't seem to work either. Not sure if VA network is blocking this port or what, but will continue debugging...

**Comment by ayaleloehr** [comment]
@cfeeney-va as you're looking at this today, figured it would also be helpful to know:
1) I added `REDIS_BASE_URL` to application.yml, as that won't be at localhost anymore if it's being stood up via the docker container. 
2) [Docker Toolbox](https://www.docker.com/products/docker-toolbox) is probably the easiest way to install docker locally to set this up.

**Comment by cfeeney-va** [comment]
Getting an additional error that seems to be related to trying to run Docker while using a VPN:

This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

**Comment by cfeeney-va** [comment]
update: docker is running correctly on my machine in the VA network, but when I attempt to access the app, i get the following error:

example url: http://192.168.99.100:3004/rx/v1/prescription

SocketError in Rx::V1::PrescriptionsController#prescription
getaddrinfo: Name does not resolve

Extracted source (around line #31):
  def authenticate(mhv_id)
    if redis.exists("sessions:#{mhv_id}")  <---THIS LINE
      return { status: 200, error: nil, data: redis.get("sessions:#{mhv_id}") }
    end

Issue seems to be linking the app to the redis instance.  I tried adding:
+  links:
+    - redis
to the "app" entry in docker-compose.yml but it didn't do anything.

Looking into the issue further.

**Comment by cfeeney-va** [comment]
entry in config/application.yml should be:
REDIS_BASE_URL: 192.168.99.100

Now getting error: "Failed to open TCP connection to admin-intb.myhealth.va.gov:443"
the first time we attempt an API call to MHV:
"return session_resp(HTTParty.get(ENV["MHV_BASE_URL"] + "session", headers: req_head), mhv_id)"

**Comment by cfeeney-va** [comment]
Docker has magically started working today.
Still can't connect to the MHV API, but works with the heroku app.  You'll need to set:

MHV_BASE_URL: https://mock-prescriptions-api.herokuapp.com/rx/v1/

in config/application.yml


to get it to work, I run the following in my terminal:
docker-machine start default
eval $(docker-machine env)
docker-compose up

**Comment by cfeeney-va** [comment]
Closing for now, as there isn't a need and we're rethinking the architecture of the app.

However, could re-use in future.

Main takeaways:
Seems very fickle; were not able to find root causes for all the issues we saw, but they resolved themselves...
Main issue was linking the redis and app
Connecting the running docker app to the VA network was an issue; hence the reliance on the heroku app

**Pull request closed without merging**
