### PR TITLE
Adding api gem related error handling

### PR DESCRIPTION
**Pull request by saneshark**
@cfeeney-va this is the template for error handling I spoke of, it's just a bit of boiler plate for now. I took the liberty of handling the client response one, but the others will be something similar - just more explicit and not necessarily based on the exception.message (more prescriptions-api specific).

### CODE REVIEW

**Comment by saneshark** [comment]
@ayaleloehr @mphprogrammer @cfeeney-va this is ready for review.

**Comment by saneshark** [comment]
It wants me to use fail instead of raise? really?!

**Comment by mphprogrammer** [comment]
That has to be wrong. Jeez.

**Comment by cfeeney-va** [comment]
LGTM

**Pull request merged**
