### PR TITLE
Apidoc apipie

### PR DESCRIPTION
**Pull request by cfeeney-va**
V1
Still to do:
-add params?
-add examples/sample responses?
-DRY out controllers?

### CODE REVIEW

**Comment by saneshark** [comment]
Talked to @cfeeney-va about this on slack, but eventually we want to consolidate errors into our own RX error messages and not the MHV messages, but I think for now it is valuable to have these documented. The only nit pick I have is, can we figure out a way to possibly move them into a concerns so they are not in the controller?

One other consideration would be -- once we have more vets.gov apis, it will be much less practical to have apis for each one available in each app server. At that point it will probably make more sense for us to have a single, maybe basic Sinatra app, for having documentation across all of the different app servers, such that it looks as though it is a single Vets.gov api for all of them.

To that end, we might want to use a tool like slate: https://github.com/lord/slate It's a separate stand alone app for documentation we could run that just does documentation. The UI is great, lets us brand it easily with Department of Veterans Affair logo, and it's just all done in Markdown which is nice, clean and easy. In fact, it's really nice because as an open source project, technically anyone would be able to comment and contribute -- We could even have disqus comment section we add to it where they can ask questions.

**Comment by saneshark** [comment]
That being said, i think this LGTM to me for now, we can revisit the points above in future PRs perhaps.

**Comment by saneshark** [comment]
@ayaleloehr tagging you for comment on this

**Comment by ayaleloehr** [comment]
Have a couple questions around the error codes:
1) It seems like the same block of code is copied in two files, which makes me worried for keeping them in sync. Is there any way around this? (or is it not actually the same block?)
2) Looks like most of the errors are a 400? I always thought of 400's being a bad request, whereas these errors are not necessarily bad requests but some problem on the Rx API side, so would like to understand this better as well.

@cfeeney-va or @saneshark happy to chat in person tomorrow morning if that's easier!

**Comment by cfeeney-va** [comment]
Closing pull request; per discussion this afternoon going to put documentation in a markdown file for now

**Pull request closed without merging**
