### PR TITLE
Use of uglifier requires execjs runtime on production

### PR DESCRIPTION
**Pull request by jkassemi**
`uglifier`  requires an execjs runtime such as node or `therubyracer`. `therubyracer` is installed as a dependency of `jshint`, but doesn't make it into the bundle when test and development gems are excluded.

Is the `uglifier` dependency something we can consider getting rid of?

### CODE REVIEW

**Comment by saneshark** [comment]
@jkassemi you'll want to update rails minor version if you haven't already. Just bump the Gemfile for rails up to the latest minor version (possibly same change for active record if it we have it fixed) then run `bundle update rails` (and bundle update active_record if applicable)

Should get bundler audit to pass.

**Comment by jkassemi** [comment]
thanks @saneshark! After review, please avoid squashing, I'd like to preserve the commit history here.

**Comment by saneshark** [comment]
LGTM

**Comment by saneshark** [comment]
@jkassemi looks like this repo is not setup to allow doing anything other merge and squash. I'll see if I can change that setting, but might need an organizational admin to do it.

**Comment by saneshark** [comment]
@jkassemi keeping your branch just in case you need it, feel free to delete it yourself.

**Comment by jkassemi** [comment]
Thanks!

**Pull request merged**
