### PR TITLE
Create api-doc.md

### PR DESCRIPTION
**Pull request by cfeeney-va**
Still to-do:
Add example responses (currently receiving error, will troubleshoot tomorrow am)

### CODE REVIEW

**Comment by saneshark** [comment]
@cfeeney-va I know this is a WIP, but just wanted to say that it already looks better to me than what I know the output of apiepie and other gems would look like and it will be so much easier to maintain for now!

One thought with this is, we have a table of contents of api endpoints which is just links to more granular endpoint specific markdown files, perhaps with *common* errors identified, and more granular ones appearing in the endpoint specific as well. We can also include JSON and curl scripts in those for making requests, expected headers, etc. But this is coming together nicely! I will work hard to get you JSON output as soon as possible.

**Comment by cfeeney-va** [comment]
thanks for the feedback @saneshark !

**Comment by ayaleloehr** [comment]
@cfeeney-va are you blocked on anything here still?

**Comment by cfeeney-va** [comment]
No, we were going to add additional features that are still in development but that can be done at a later time.  This is good to merge as a first pass.

**Comment by ayaleloehr** [comment]
Trying to understand why we are returning a 400 for all these various errors that a 400 doesn't seem to fit well for.  Talking to @cfeeney-va , it sounds like this is just what the Rx API returns and we are passing it through. In the future we should probably return more accurate error numbers, but for now this PR represents the current truth and is our first documentation, so it is an infinite improvement over current state and thus should be merged. :)

LGTM.

**Pull request merged**
